[package]
name = "weblib"
version = "0.1.0"
authors = ["Sander Hahn <sanderhahn@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.68"
js-sys = "0.3.45"
web-sys = { version = "0.3.45", features = ["console"] }
